spring:
  application:
    name: PolyPaste

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  datasource:
    url: jdbc:postgresql://localhost:5439/Poly_Paste
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

rabbitmq:
  queue:
    name: poly_paste_queue
  exchange:
    name: poly_paste_exchange
  routing:
    key: poly_paste_key

jwt:
  secret: 5JzoMbk6E5qIqHSuBTgeQCARtUsxAkBiHwdjXOSW8kWdXzYmP3X51C0

vk:
  app-id: 54580162
  client-secret: 'g9ngmnjjDNDim7n38lpm'
  redirect-uri: https://9je8ur-178-66-156-216.ru.tuna.am/auth/vk/callback

server:
  address: 127.0.0.1
  port: 8080
  forward-headers-strategy: native
  ssl:
    enabled: false
    key-store: classpath:keystore.p12
    key-store-password: Garfield2008
    key-store-type: PKCS12
    key-alias: springboot