spring:
  application:
    name: PolyPaste

  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  datasource:
    url: jdbc:postgresql://localhost:5439/Poly_Paste
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  rabbitmq:
    queue:
      input: q1
      output: q2
    exchange: moderation-exchange
    routing-key:
      input: moderation.input
      output: moderation.output
  ml:
    model-path: src/main/resources/models/rubert-tiny-toxic.onnx
    threshold: 0.3

  minio:
    endpoint: http://localhost:9000
    access-key: admin
    secret-key: admin
    bucket: pastes
    auto-create-bucket: true

jwt:
  secret: 5JzoMbk6E5qIqHSuBTgeQCARtUsxAkBiHwdjXOSW8kWdXzYmP3X51C0

vk:
  app-id: 54580162
  client-secret: 'DMMaDDCHTGmwcFb0JfU9'
  redirect-uri: http://localhost/auth/vk/callback

server:
  address: 0.0.0.0
  port: 80

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /v3/api-docs