spring.application.name=PolyPaste

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin

rabbirmq.queue.name=poly_paste_queue
rabbirmq.exchange.name=poly_paste_exchange
rabbirmq.routing.key=poly_paste_key

spring.datasource.url=jdbc:postgresql://localhost:5439/Poly_Paste
spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true